services:
   db:
     image: postgres
     restart: always
     environment:
       POSTGRES_PASSWORD: anime
       POSTGRES_USER: anime
       POSTGRES_DB: anime
       PGDATA: /data/postgres
     volumes:
       - db:/data/postgres
   redis:
     image: redislabs/redismod
     ports:
       - '6379:6379'
   dramatiq:
     build: .
     command: dramatiq endpoints.anime --processes 1 --threads 3
     depends_on:
       - redis
     volumes:
       - .:/code
   web:
     build: .
     command: ["uvicorn", "main:app", "--host", "0.0.0.0",]
     ports:
       - "8000:8000"
     volumes:
       - .:/code
     depends_on:
       - redis
       - db


volumes:
  db: